from .trainer import Trainer


def populate(client):
    intents = Trainer("intents", client)
    intents.add_to_traingset("Guten Tag", "greeting", True)
    intents.add_to_traingset("Good day", "greeting", True)
    intents.add_to_traingset("Hallo", "greeting", True)
    intents.add_to_traingset("Hello", "greeting", True)
    intents.add_to_traingset("Hey", "greeting", True)
    intents.add_to_traingset("Hi", "greeting", True)
    intents.add_to_traingset("Servus", "greeting", True)
    intents.add_to_traingset("Grüß Gott", "greeting", True)
    intents.add_to_traingset("Grüße", "greeting", True)
    intents.add_to_traingset("Ave", "greeting", True)
    intents.add_to_traingset("Bonjour", "greeting", True)
    intents.add_to_traingset("Guten Morgen", "greeting", True)
    intents.add_to_traingset("Good morning", "greeting", True)
    intents.add_to_traingset("Guten Abend", "greeting", True)
    intents.add_to_traingset("Good evening", "greeting", True)
    intents.add_to_traingset("hello, good morning", "greeting", True)
    intents.add_to_traingset("hello, good evening", "greeting", True)
    intents.add_to_traingset("Moin", "greeting", True)
    intents.add_to_traingset("Can you tell me a joke?", "joke", True)
    intents.add_to_traingset("Erzähl mir einen Witz", "joke", True)
    intents.add_to_traingset("Erzähl mir etwas witziges", "joke", True)
    intents.add_to_traingset("Erzähl mir etwas lustiges", "joke", True)
    intents.add_to_traingset("Fun", "joke", True)
    intents.add_to_traingset("Funny", "joke", True)
    intents.add_to_traingset("Joke", "joke", True)
    intents.add_to_traingset("Kannst du mir einen Witz erzählen?", "joke", True)
    intents.add_to_traingset("Lachen", "joke", True)
    intents.add_to_traingset("Bring mich zum Lachen", "joke", True)
    intents.add_to_traingset("Laugh", "joke", True)
    intents.add_to_traingset("Tell me a joke", "joke", True)
    intents.add_to_traingset("Tell me something funny", "joke", True)
    intents.add_to_traingset("Witz", "joke", True)
    intents.add_to_traingset("Unterhalte mich", "joke", True)
    intents.add_to_traingset("Dinner", "meal", True)
    intents.add_to_traingset("Eating", "meal", True)
    intents.add_to_traingset("Essen", "meal", True)
    intents.add_to_traingset("Food", "meal", True)
    intents.add_to_traingset("Lunch", "meal", True)
    intents.add_to_traingset("Meal", "meal", True)
    intents.add_to_traingset("Mensa", "meal", True)
    intents.add_to_traingset("Ich habe Hunger", "meal", True)
    intents.add_to_traingset("Was gibt es zu Essen", "meal", True)
    intents.add_to_traingset("Was gibt es in der Mensa", "meal", True)
    intents.add_to_traingset("Garnicht", "notAtAll", True)
    intents.add_to_traingset("Not at all", "notAtAll", True)
    intents.add_to_traingset("Give me my timetable", "timetables", True)
    intents.add_to_traingset("Lecture", "timetables", True)
    intents.add_to_traingset("Stundenplan", "timetables", True)
    intents.add_to_traingset("Time table", "timetables", True)
    intents.add_to_traingset("Timetable", "timetables", True)
    intents.add_to_traingset("Was habe ich heute?", "timetables", True)
    intents.add_to_traingset("Welche Vorlesung hab ich heute?", "timetables", True)
    intents.add_to_traingset("What lecture do i have today?", "timetables", True)
    intents.add_to_traingset("What's on my schedule?", "timetables", True)
    intents.add_to_traingset("Wie sieht mein Tag aus?", "timetables", True)
    intents.add_to_traingset("Tell me about my day", "timetables", True)
    intents.add_to_traingset("Show me my schedule", "timetables", True)
    intents.add_to_traingset("Zeig mir meinen Stundenplan", "timetables", True)
    intents.add_to_traingset("weather", "weather", True)
    intents.add_to_traingset("Wie ist das Wetter?", "weather", True)
    intents.add_to_traingset("Wie wird das Wetter heute?", "weather", True)
    intents.add_to_traingset("Wird es heute schön?", "weather", True)
    intents.add_to_traingset("Wie ist es draußen", "weather", True)
    intents.add_to_traingset("Regnet es?", "weather", True)
    intents.add_to_traingset("Scheint die Sonne?", "weather", True)
    intents.add_to_traingset("Brauche ich einen Regenschirm?", "weather", True)
    intents.add_to_traingset("Brauche ich einen Schirm?", "weather", True)
    intents.add_to_traingset("Wie kalt ist es draußen?", "weather", True)
    intents.add_to_traingset("Wie warm ist es draußen?", "weather", True)
    intents.add_to_traingset("Brauche ich eine Jacke?", "weather", True)
    intents.add_to_traingset("Wer bist du?", "who", True)
    intents.add_to_traingset("Who are you?", "who", True)
    intents.start_training()

    entities_for_meal = Trainer("entities@meal", client)
    entities_for_meal.add_to_traingset("1", "essen1")
    entities_for_meal.add_to_traingset("Wahlessen 1", "essen1")
    entities_for_meal.add_to_traingset("One", "essen1")
    entities_for_meal.add_to_traingset("Eins", "essen1")
    entities_for_meal.add_to_traingset("2", "essen2")
    entities_for_meal.add_to_traingset("Wahlessen 2", "essen2")
    entities_for_meal.add_to_traingset("Two", "essen2")
    entities_for_meal.add_to_traingset("Zwei", "essen2")
    entities_for_meal.add_to_traingset("3", "aktionstheke")
    entities_for_meal.add_to_traingset("Aktionstheke", "aktionstheke")
    entities_for_meal.add_to_traingset("Three", "aktionstheke")
    entities_for_meal.add_to_traingset("Drei", "aktionstheke")
    entities_for_meal.add_to_traingset("4", "gutundguenstig")
    entities_for_meal.add_to_traingset("Gut & Günstig", "gutundguenstig")
    entities_for_meal.add_to_traingset("Gut und Günstig", "gutundguenstig")
    entities_for_meal.add_to_traingset("Four", "gutundguenstig")
    entities_for_meal.add_to_traingset("Vier", "gutundguenstig")
    entities_for_meal.add_to_traingset("5", "buffet")
    entities_for_meal.add_to_traingset("Fünf", "buffet")
    entities_for_meal.add_to_traingset("Five", "buffet")
    entities_for_meal.add_to_traingset("Buffet", "buffet")
    entities_for_meal.add_to_traingset("6", "schnitzelbar")
    entities_for_meal.add_to_traingset("Schnitzelbar", "schnitzelbar")
    entities_for_meal.add_to_traingset("Six", "schnitzelbar")
    entities_for_meal.add_to_traingset("Sechs", "schnitzelbar")
    entities_for_meal.start_training()

    entities_for_timetables = Trainer("entities@timetables", client)
    entities_for_timetables.add_to_traingset("1", "Montag")
    entities_for_timetables.add_to_traingset("Monday", "Montag")
    entities_for_timetables.add_to_traingset("Montag", "Montag")
    entities_for_timetables.add_to_traingset("2", "Dienstag")
    entities_for_timetables.add_to_traingset("Tuesday", "Dienstag")
    entities_for_timetables.add_to_traingset("Dienstag", "Dienstag")
    entities_for_timetables.add_to_traingset("3", "Mittwoch")
    entities_for_timetables.add_to_traingset("Mittwoch", "Mittwoch")
    entities_for_timetables.add_to_traingset("Wednesday", "Mittwoch")
    entities_for_timetables.add_to_traingset("4", "Donnerstag")
    entities_for_timetables.add_to_traingset("Thursday", "Donnerstag")
    entities_for_timetables.add_to_traingset("Donnerstag", "Donnerstag")
    entities_for_timetables.add_to_traingset("5", "Freitag")
    entities_for_timetables.add_to_traingset("Friday", "Freitag")
    entities_for_timetables.add_to_traingset("Freitag", "Freitag")
    entities_for_timetables.add_to_traingset("6", "Samstag")
    entities_for_timetables.add_to_traingset("Saturday", "Samstag")
    entities_for_timetables.add_to_traingset("Samstag", "Samstag")
    entities_for_timetables.add_to_traingset("7", "Sonntag")
    entities_for_timetables.add_to_traingset("Sunday", "Sonntag")
    entities_for_timetables.add_to_traingset("Sonntag", "Sonntag")
    entities_for_timetables.start_training()

